protocol:
  selector:
    config:
      - 
        size: 2 
        percent: 100
      -
        size: 3
        percent: 67
      -
        size: 4
        percent: 75
      -
        size: 5
        percent: 80