protocol:
  selector:
    config:
      - 
        size: 2 
        quorum: 1.00
      -
        size: 3
        quorum: 0.66
      -
        size: 4
        quorum: 0.75
      -
        size: 5
        quorum: 0.80